/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.CardLayout;
import javax.swing.JFrame;

/**
 *
 * @author Pablo Sierralta
 */
public class FrameMain extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public FrameMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jPanelBienvenida = new view.JPanelBienvenida();
        jPanelRegistrartInscripcion = new view.JPanelRegistrartInscripcion();
        jPanelCorredoresMain = new view.JPanelCorredoresMain();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenuOperaciones = new javax.swing.JMenu();
        jMenuItemCorredores = new javax.swing.JMenuItem();
        jMenuItemInscripcion = new javax.swing.JMenuItem();
        jMenuAyuda = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ficha de Inscripción");
        setAlwaysOnTop(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanelMain.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanelBienvenidaLayout = new javax.swing.GroupLayout(jPanelBienvenida);
        jPanelBienvenida.setLayout(jPanelBienvenidaLayout);
        jPanelBienvenidaLayout.setHorizontalGroup(
            jPanelBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1258, Short.MAX_VALUE)
        );
        jPanelBienvenidaLayout.setVerticalGroup(
            jPanelBienvenidaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 562, Short.MAX_VALUE)
        );

        jPanelMain.add(jPanelBienvenida, "card4");
        jPanelMain.add(jPanelRegistrartInscripcion, "card5");
        jPanelMain.add(jPanelCorredoresMain, "card4");

        getContentPane().add(jPanelMain);

        jMenuOperaciones.setText("Operaciones");

        jMenuItemCorredores.setText("Gestionar Corredores");
        jMenuItemCorredores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCorredoresActionPerformed(evt);
            }
        });
        jMenuOperaciones.add(jMenuItemCorredores);

        jMenuItemInscripcion.setText("Registrar Inscripción");
        jMenuItemInscripcion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemInscripcionActionPerformed(evt);
            }
        });
        jMenuOperaciones.add(jMenuItemInscripcion);

        jMenuBarPrincipal.add(jMenuOperaciones);

        jMenuAyuda.setText("Ayuda");

        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenuAyuda.add(jMenuItem1);

        jMenuBarPrincipal.add(jMenuAyuda);

        setJMenuBar(jMenuBarPrincipal);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCorredoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCorredoresActionPerformed
        
        CardLayout card = (CardLayout) jPanelMain.getLayout();
        card.show(jPanelMain, "card4");
    }//GEN-LAST:event_jMenuItemCorredoresActionPerformed

    private void jMenuItemInscripcionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemInscripcionActionPerformed
        CardLayout card = (CardLayout) jPanelMain.getLayout();
        card.show(jPanelMain, "card5");
    }//GEN-LAST:event_jMenuItemInscripcionActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
                JDialogCorredoresRegistrar reg = new JDialogCorredoresRegistrar(this, true);
        reg.pack();
        reg.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            FrameMain frame = new FrameMain();
            frame.setVisible(true);
            frame.setExtendedState(JFrame.MAXIMIZED_BOTH);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenuAyuda;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItemCorredores;
    private javax.swing.JMenuItem jMenuItemInscripcion;
    private javax.swing.JMenu jMenuOperaciones;
    private view.JPanelBienvenida jPanelBienvenida;
    private view.JPanelCorredoresMain jPanelCorredoresMain;
    private javax.swing.JPanel jPanelMain;
    private view.JPanelRegistrartInscripcion jPanelRegistrartInscripcion;
    // End of variables declaration//GEN-END:variables
}
